image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo 
  - ls -lrth
  - cd public && ls -lrth  resources/*
  artifacts:
    paths:
    - public
  only:
  - master
